name: mongo-multi-modal-search-v2
applications:
  - name: frontend
    route_prefix: /
    import_path: frontend:app
    # deployments:
    #   - name: gradio-frontend
    #     num_replicas: 1
  - name: backend
    route_prefix: /backend
    import_path: backend:app
    # deployments:
    #   - name: search-backend
    #     num_replicas: 1
query_auth_token_enabled: false