name: mongo-multi-modal-search-v2
applications:
  - name: frontend
    route_prefix: /
    import_path: frontend:app
  - name: backend
    route_prefix: /backend
    import_path: backend:app 1
query_auth_token_enabled: false
requirements: requirements.txt
